import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateShipmentPDF = (shipment: any) => {
  const doc = new jsPDF();

  // ===== Header =====
  doc.setFontSize(22);
  doc.setTextColor(30, 64, 175);
  doc.text("ChainShield AI", 14, 20);

  doc.setFontSize(14);
  doc.setTextColor(80);
  doc.text("Shipment Risk Assessment Report", 14, 30);

  doc.setDrawColor(59, 130, 246);
  doc.line(14, 35, 195, 35);

  // ===== Shipment Details =====
  autoTable(doc, {
    startY: 45,
    head: [["Field", "Value"]],
    body: [
      ["Order ID", shipment["Order Id"]],
      ["Order Date", shipment["Order Date"]],
      ["Customer City", shipment["Customer City"]],
      ["Customer State", shipment["Customer State"]],
      ["Shipping Mode", shipment["Shipping Mode"]],
      ["Risk Level", shipment["AI Risk"]],
      [
        "Prediction",
        shipment["Prediction"] === 1 ? "Delayed" : "On Time",
      ],
      ["Confidence", `${shipment["Confidence"]}%`],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [37, 99, 235],
    },
  });

  // ===== AI Summary =====
  const finalY = (doc as any).lastAutoTable.finalY + 15;

  doc.setFontSize(16);
  doc.setTextColor(30, 64, 175);
  doc.text("AI Summary", 14, finalY);

  doc.setFontSize(12);
  doc.setTextColor(60);

  const summary =
    shipment["AI Risk"] === "High"
      ? "This shipment has been classified as HIGH RISK. Immediate monitoring and operational review are recommended."
      : shipment["AI Risk"] === "Medium"
      ? "This shipment has a MODERATE RISK. Continue monitoring until delivery."
      : "This shipment is LOW RISK and is expected to proceed normally.";

  const lines = doc.splitTextToSize(summary, 180);

  doc.text(lines, 14, finalY + 10);

  // ===== Footer =====
  doc.setFontSize(10);
  doc.setTextColor(120);

  doc.text(
    `Generated on ${new Date().toLocaleString()}`,
    14,
    285
  );

  doc.text(
    "Generated by ChainShield AI",
    140,
    285
  );

  // ===== Download =====
  doc.save(`Shipment_${shipment["Order Id"]}.pdf`);
};